theme: jekyll-theme-cayman
nav:
  - title: "Rotterdam's Golden View"
    url: ""
  - title: "Planning"
    url: "/webpages/planning.md"
  - title: "Configuring"
    url: "/webpages/configuring.md"
  - title: "Massing"
    url: "/webpages/massing.md"
  - title: "Forming"
    url: "/webpages/forming.md"
  - title: "Water"
    url: "/webpages/water.md"
  - title: "Reflections"
    url: "/webpages/reflections.md"
    
