title: Rotterdam's Golden View
description: Bob's Building crew for Schiestraat Rotterdam
url: "https://JeroenTUDelft.github.io"

nav:
  - title: "Rotterdam's Golden View"
    url: ""
  - title: "Planning"
    url: "/webpages/planning/"
  - title: "Configuring"
    url: "/webpages/configuring/"
  - title: "Massing"
    url: "/webpages/massing/"
  - title: "Forming"
    url: "/webpages/forming/"
  - title: "Water and Energy Calculations"
    url: "/webpages/water and energy calculations.md/"
  - title: "Reflections"
    url: "/webpages/reflections/"

theme: jekyll-theme-cayman
